### ISSUE TITLE
Add patch level versioning to tags in docker repository

### ISSUE THREAD

**Issue by aensidhe** [tarantool/docker#11]
Example: https://hub.docker.com/r/mhart/alpine-node/tags/

It is very usable to be able to pin version of tarantool in a more specific way than 1.7.

**Comment by rtsisyk** [comment]
Hi @aensidhe, all our minor releases are backward-compatible and contain mostly bugfixes.
We usually don't support 1.7.$((x-1)) after release of 1.7.x.

**Comment by racktear** [comment]
I think it is reasonable. And it is not that hard to implement.

**Comment by aensidhe** [comment]
@rtsisyk this will be true after release of 1.7. Right now it is in beta, you did breaking changes to protocol. Also, there could be bugs in client or whatever. 

I do not ask about actually supporting as fixes to some concrete minor versions. I do ask about ability to fix some version to maintain consistence through all clusters: develop, test, stage, production to have one concrete build.
