### ISSUE TITLE
Link in dockerhub docs is broken

### ISSUE THREAD

**Issue by denismitr** [tarantool/docker#110]
Here at [https://hub.docker.com/r/tarantool/tarantool/](https://hub.docker.com/r/tarantool/tarantool/)

> If you need a remote console via TCP/IP, use tarantoolctl utility as explained here.

Link under `here` leads to 404 page

**Comment by Totktonada** [comment]
@lenkis This is the link to `https://www.tarantool.io/en/doc/1.10/administration/#administration-tarantoolctl-connect` in README.md in this repository.

**Comment by denismitr** [comment]
Ok, but it is still a broken link

**Comment by patiencedaur** [comment]
@Totktonada We don't have access to Dockerhub, but the correct link is: https://www.tarantool.io/en/doc/latest/reference/tarantoolctl/

**Comment by Totktonada** [comment]
Docs on Docker Hub are crawled from README.md.

**Comment by Totktonada** [comment]
Automated deployments offered by Docker Hub are disabled now (to be replaced with more flexible pushing from CI, see #187) and so README.md is not updated on the Docker Hub page automatically. I changed it manually.
