### ISSUE TITLE
Benchmark Tarantool on musl libc (Alpine Linux) vs Tarantool on glibc (Debian/Ubuntu/etc.)

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/docker#12]
![unspecified](https://cloud.githubusercontent.com/assets/1799054/19525212/426695da-9631-11e6-951a-95d82b37ed5b.png)

5 - Tarantool 1.5.5-1-g6aaa312  from tarantool/tarantool:1.5 hub.docker.com (Alpine Linux)
6 - Tarantool 1.5.5-1-g6aaa312 from sources on Debian Jessie

Reported by @banuchka on Telegram Channel.

**Comment by banuchka** [comment]
All tests was made on SLES 11.3 and 12 except number 5. We don't use Debian...

**Comment by kyukhin** [comment]
We do not support Tarantool 1.5 anymore and do not see any demand for the issue. Feel free to re-open if concerned.
