### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by Totktonada** [tarantool/docker#127]
Verify that each image can be built and tarantool able to run inside the built image.

**Comment by avtikhon** [comment]
First of all we need the administrative access to the gitlab-ci of this project to switch on the synchronization/pulling of the sources from github.
I've tried to build the images and it failed, also I didn't find the reasons for some changes - I've wrote the comments to #126

**Comment by Totktonada** [comment]
We didn't intend to use GitLab CI anywhere aside tarantool/tarantool repository, see https://github.com/tarantool/tarantool/issues/4156. I think it is better to use externally maintained infrastructure when possible. I propose to use GitHub Actions or Travis-CI.

**Comment by avtikhon** [comment]
For now we already have the gitlab-ci testing at this repository, let's just check it updated to be able to measure the differences in use with the solutions at other CI structures, anyway it is already exists and don't need any activity except switch back on and minor update to gitlab-ci.yml file.

**Comment by avtikhon** [comment]
Done
