### ISSUE TITLE
Add luautf8 luarock to docker image

### ISSUE THREAD

**Issue by roman-kozachenko** [tarantool/docker#13]
Since LuaJIT doesn't support utf8 out of the box it will be useful to add [luautf8](https://github.com/starwing/luautf8) to docker image.

**Comment by bigbes** [comment]
@roman-kozachenko, maybe you should use this image as base image, rather than add everything inside image?

**Comment by Totktonada** [comment]
Now we have built-in utf8 module in tarantool 1.10.2. It does not have all functions from Lua's 5.3 utf8 nor from starwing/luautf8, but handles much needed cases.

**Comment by NickVolynkin** [comment]
We have utf8 bundled in Tarantool 1.10 and 2.x, so there's no need to bundle an external module with the same purpose.
