### ISSUE TITLE
missing checkpoint_count configuration

### ISSUE THREAD

**Issue by nekufa** [tarantool/docker#143]
Right now there is an `TARANTOOL_CHECKPOINT_INTERVAL` environment option.
We need `TARANTOOL_CHECKPOINT_COUNT` one that will configure `box.cfg.checkpoint_count`.

**Comment by nekufa** [comment]
@knazarov what do you think about this option?

**Comment by kyukhin** [comment]
Done here https://github.com/tarantool/tarantool/issues/5602
