### ISSUE TITLE
Dockerfile: failed pprof installation

### ISSUE THREAD

**Issue by avtikhon** [tarantool/docker#147]
Avoid of fails of additional pprof tool

Found that pprof tool installation became broken at the
github sources. Left the pprof tool installation at the
docker files but disabled it's return code to avoid of
iamges building failures dut to pprof was additional.
Error on pprof installation found:

$ sudo snap install go --classic
go 1.14.3 from Michael Hudson-Doyle (mwhudson) installed

$ GOPATH=/usr/src/go go get github.com/google/pprof ; echo $?
/usr/src/go/src/github.com/google/pprof/internal/driver/settings.go:27:14: undefined: os.UserConfigDir
2

**Comment by Totktonada** [comment]
Reason: https://github.com/google/pprof/issues/538
