### ISSUE TITLE
Luarocks uses wrong wget instead of curl in tarantool 1.10.4

### ISSUE THREAD

**Issue by asnelzin** [tarantool/docker#170]
Seems like in dockerhub version of tarantool 1.10.4 luarocks uses broken/wrong version of wget, and this leads to the inability to install any lua package.

Following command dont work:
`docker run -i tarantool/tarantool:1.10.4 luarocks install --verbose expirationd`

Error:
```
Warning: Failed searching manifest: Failed fetching manifest for http://rocks.tarantool.org/ - Failed downloading http://rocks.tarantool.org/manifest - /root/.cache/luarocks/http___rocks.tarantool.org_/manifest
wget: unrecognized option: timestamping
BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.

Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
	[--header 'header: value'] [-Y|--proxy on/off] [-P DIR]
	[-S|--server-response] [-U|--user-agent AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

	--spider	Only check URL existence: $? is 0 if exists
	-c		Continue retrieval of aborted transfer
	-q		Quiet
	-P DIR		Save to DIR (default .)
	-S    		Show server response
	-T SEC		Network read timeout is SEC seconds
	-O FILE		Save to FILE ('-' for stdout)
	-U STR		Use STR for User-Agent header
	-Y on/off	Use proxy
```

**Comment by avtikhon** [comment]
Tarantool 1.10.4 failed to build on alpine 3.5, but successfully initially built on alpine 3.9. This image version was uploaded. Unfortunately wget from BusyBox in there changed too and doesn't support some old flags:
- alpine 3.5: BusyBox v1.25.1 (2018-05-30 19:58:18 GMT) multi-call binary.
- alpine 3.9: BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.
