### ISSUE TITLE
Overcome Docker Hub image retention policy

### ISSUE THREAD

**Issue by Totktonada** [tarantool/docker#188]
> Docker is introducing a container image retention policy which will be enforced starting November 1, 2020.

> Image retention is based on the activity of each individual image stored within a user account. If an image has not either been pulled or pushed in the amount of time specified in your subscription plan, the image will be tagged “inactive.” Any images that are tagged as “inactive” will be scheduled for deletion.

https://www.docker.com/pricing/retentionfaq

https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/

It seems, periodical pull of all tags should help. We should automate this task.

**Comment by Totktonada** [comment]
As pointed by @rosik:

> We detailed the following pull rate limits to Docker subscription plans that will take effect November 1, 2020:
>
> * Free plan – anonymous users: 100 pulls per 6 hours 
> * Free plan – authenticated users: 200 pulls per 6 hours

https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/

**Comment by NickVolynkin** [comment]
Oct 22 2020: 

> we are pausing enforcement of the changes to image retention until mid 2021

now retention is not a part of Docker plans and pricing
