### ISSUE TITLE
Add snap_dir and wal_dir to env

### ISSUE THREAD

**Issue by donmikel** [tarantool/docker#19]
Add snap_dir and wal_dir to be able to set through "docker run"

**Comment by racktear** [comment]
@donmikel Why do you need to set them? It is expected that tarantool writes its data to /var/lib/tarantool in this container.

**Comment by donmikel** [comment]
I need to have separate snap_dir from wal_dir to place it to several disk due performance case.

**Comment by racktear** [comment]
Discussed in person. I don't think that container environment variables are a good place to store that information, as it's relatively static. 

Instead, in your own lua code you can do as follows:

```lua
box.cfg{
    ...
    wal_dir = os.getenv('TARANTOOL_WAL_DIR'); 
    ...
}
```
