### ISSUE TITLE
Provide frozen CentOS 7 based images

### ISSUE THREAD

**Issue by Totktonada** [tarantool/docker#199]
Currently we have the following docker tags for images based on CentOS 7: `1.x-centos7` and `2.x-centos7`. We update them when new releases are published.

I think we should provide frozen `1.10.8-centos7` and `2.5.2-centos7` as well and add the new ones when the new releases will come.

**Comment by NickVolynkin** [comment]
@Totktonada we build and publish CentOS-based images with fixed tags. For example, with 2.10.2:

* [2.10.2-gc64-centos7-amd64](https://hub.docker.com/layers/tarantool/tarantool/2.10.2-gc64-centos7-amd64/images/sha256-425dd7b60e41dab6b45174646380675e621fe65997bf995bb2da751a6733cb46?context=explore)
* [2.10.2-nogc64-centos7-amd64](https://hub.docker.com/layers/tarantool/tarantool/2.10.2-nogc64-centos7-amd64/images/sha256-338b1f7b77e4e8feb89027c35e4e53914ba48f3660895372ad5192437f155bdf?context=explore)
* [2.10.2-gc64-centos7-aarch64](https://hub.docker.com/layers/tarantool/tarantool/2.10.2-gc64-centos7-aarch64/images/sha256-4c31c556a3f3e6bd2d4d33880d1260655140680d8d8f6f57590e5517d8ea1fb8?context=explore)

It's far from perfect, but seems enough to close this issue.

**Comment by Totktonada** [comment]
I don't mind. However I would highlight that it would be nice to keep the [tables of tags](https://github.com/tarantool/docker#build-pipelines) in the README actual.
