### ISSUE TITLE
How to make queue available globally at beginning?

### ISSUE THREAD

**Issue by kokizzu** [tarantool/docker#200]
I need to run this command at beginning `queue = require 'queue'`:
```
$ docker exec -it full_tarantool_1 console
#connected to unix/:/var/run/tarantool/tarantool.sock
#unix/:/var/run/tarantool/tarantool.sock> queue = require 'queue'
```

How to do this when using `tarantool/tarantool` docker?
Should I change the `tarantool-entrypoint.lua`?

**Comment by Totktonada** [comment]
There are two variants of running a Lua code within the container:

1. [Adding application code with a volume mount](https://github.com/tarantool/docker#adding-application-code-with-a-volume-mount).
2. [Adding application code using container inheritance](https://github.com/tarantool/docker#adding-application-code-using-container-inheritance).

In your code you should also [create a tube](https://github.com/tarantool/queue#creating-a-new-queue) and [grant](https://github.com/tarantool/queue/issues/114) privileges to allow a connector to work with the tube.

**Comment by Totktonada** [comment]
If you still have questions around using the tarantool/queue module in the docker container, feel free to reopen and ask.
