### ISSUE TITLE
Rebuild image with new Curl changes

### ISSUE THREAD

**Issue by vmakhaev** [tarantool/docker#23]
@dedok rewrote curl and fixed some bugs, let's rebuild docker image with these changes

**Comment by vmakhaev** [comment]
Release https://github.com/tarantool/curl/releases/tag/2.2.3

**Comment by racktear** [comment]
Updated tarantool/tarantool:1.7 and tarantool/tarantool:1.6

**Comment by rtsisyk** [comment]
Please note that tarantool-curl API is still in flux (see https://github.com/tarantool/curl/issues/12).
