### ISSUE TITLE
Unable to run master-master replica in Docker Swarm

### ISSUE THREAD

**Issue by grachevko** [tarantool/docker#29]
Same issue as this https://github.com/minio/minio/pull/4799

> Swarm routes traffic only to containers that report healthy status, while Minio in distributed mode needs to talk to other peers before it can respond to healthcheck probe. As the Minio containers are not able to talk to each other, distributed Minio is not getting started on Docker Swarm.

**Comment by NickVolynkin** [comment]
I doubt that we will ever support Docker Swarm.
