### ISSUE TITLE
In 1.7+ old option names for `box.cfg` are used

### ISSUE THREAD

**Issue by bigbes** [tarantool/docker#34]
https://github.com/tarantool/docker/blob/master/1.7/tarantool-entrypoint.lua#L208-L211 and other places

**Comment by Totktonada** [comment]
It lead to unablility to set memtx_dir from user’s box.cfg{}.

> Incorrect value for option 'snap_dir': can not override a value for a deprecated option

It is because of tarantool-entry.lua, but very similar code is in docker-entrypoint.lua (I think both should be fixed).
