### ISSUE TITLE
Docker image should have more tags

### ISSUE THREAD

**Issue by nekufa** [tarantool/docker#41]
It will be good to implement same version strategy as progaudi/docker
# Version strategy

Every build of Tarantool from stable branches is tagged (e.g. branch is 1.7): 1.7.5-123-g234dsa, which can be broken into parts:
- 1.7 is major version
- 5 is minor version
- 123-g234dsa is build version

If we would build an image from that commit, we'll push tags:
- major version (1.7)
- minor version (1.7.5)
- package version (1.7.5-123-g234dsa)

In this way we achieve a couple of interesting things. 1.7 is the latest 1.7 build, so if you care only about major version, use this tag. If you care about specific minor version, then stick to minor version tag (1.7.5). But my recommendation is to stick to most detailed tag (package version).

Please, check out https://hub.docker.com/r/progaudi/tarantool/tags/

**Comment by racktear** [comment]
I only tag release versions. There is already 1.7 which should point to the latest release of 1.7, and 1.7.x, which is updated on every release.

**Comment by sharonovd** [comment]
Right now 1.7.5 and 1.7.6 tags are missing

**Comment by nekufa** [comment]
I know how it works now, and it will be good to change it as described above

**Comment by racktear** [comment]
major/minor version scheme works as you say right now. Correct me if I'm wrong here.
There are no plans to build pre-release versions automatically. And to be frank, I'm opposed to this idea in general.

**Comment by nekufa** [comment]
`Correct me if I'm wrong here`
Currently there are no 1.7.5 and 1.7.6 tags. 

`There are no plans to build pre-release versions automatically. `
For 1.7.5 branch there were to much issues that affected our installation. I want to lock on 1.7.5-0 version and move on carefully. But official image has no tags for packages inside minor releases.

In addition, pre-release versions are published to package managers, i think it will be good to do the same way for docker images.

**Comment by racktear** [comment]
@nekufa I've created 1.7.5 and 1.7.6 tags on docker hub. They refer to tarantool's released versions as you'd expect. In future, we'd try to tag them more carefully, right on tarantool releases.

There would be no pre-release docker container builds for the time being.
