### ISSUE TITLE
Rename deprecated parameters

### ISSUE THREAD

**Issue by bofm** [tarantool/docker#42]
Some parameters were renamed in 1.7. These parameters which are set through env variables in docker should be renamed accordingly. For instance, TARANTOOL_SLAB_ALLOC_ARENA should be renamed to TARANTOOL_MEMTX_MEMORY.

**Comment by racktear** [comment]
@bofm actually, both TARANTOOL_MEMTX_MEMORY and TARANTOOL_SLAB_ALLOC_ARENA should work. TARANTOOL_SLAB_ALLOC_ARENA is kept for backward compatibility.
