### ISSUE TITLE
Getting UTC timestamp in tarantool container

### ISSUE THREAD

**Issue by IzmaylovAndrey** [tarantool/docker#43]
I'm new with Lua and I have a small problem. I need UTC timestamp in my tarantool script, but when I tried to get timestamp on docker instance such way:
```
unix/:/var/run/tarantool/tarantool.sock> os.time(os.date("!*t"))
---
- 1516295913
...
```

I've got timestamp in my local TZ.
```
unix/:/var/run/tarantool/tarantool.sock> os.difftime(os.time(), os.time(os.date("!*t")))
---
- 0
...

```
BTW, when I tried to reproduce it in tarantool instance on my local machine, I got correct result:
```
tarantool> os.time(os.date("!*t"))
---
- 1516285420
...

tarantool> os.difftime(os.time(), os.time(os.date("!*t")))
---
- 10800
...

```
How can I resolve this problem?

**Comment by racktear** [comment]
@IzmaylovAndrey use `clock.time()`: https://www.tarantool.org/ru/doc/1.7/reference/reference_lua/clock.html#clock-time

**Comment by IzmaylovAndrey** [comment]
@racktear Thanx
