### ISSUE TITLE
Running a read only Replica in Docker container

### ISSUE THREAD

**Issue by a-belyaev** [tarantool/docker#49]
What is the proper way of running readonly replica in a Docker container? There is no parameter (environment variable) that can be used for that. I can set replica_sources but can't set read only mode for replicas thou it's recommended.

**Comment by kyukhin** [comment]
All options are now duplicated w/ env vars.
See [TT_READ_ONLY](https://www.tarantool.io/en/doc/latest/reference/configuration/#confval-read_only)
